[[headers]]
  for = "/*"
  [headers.values]
    # HTML should update fast
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Assets can be cached long-term
    Cache-Control = "public, max-age=31536000, immutable"
